### ISSUE TITLE
Check the initial conditions - blame streamlit or model?

### ISSUE THREAD

**Issue by danhammer** [earthrise-media/covid-model#2]
If you set the initial infection rates, the graphs don't seem to reflect the starting condition.  That is, suppose I set the initial condition to something crazy -- like 20% of the population.  The initial conditions don't seem to reflect that.  

https://github.com/earthrise-media/covid-model/blob/90594b9eef5cf2984220beecd32ce45fd3a90d60/simpleapp.py#L28-L33

**Comment by eboyda** [comment]
It's definitely a streamlit / plotting problem. The dataframe is correctly updating, which you can see if you put in an st.write(infected) after:
df = res.solve_to_dataframe(pop_0.flatten())
infected = df[df["Group"] == "Infected"]

**Comment by eboyda** [comment]
Get this. If you change the 'Initial rate of infection' and then _increase_ the 'Start day', the graph makes both updates. If you _decrease_ the 'Start day' or only change the 'Initial rate of infection', the graph does not update at all. The dataframe changes correctly in response to any change.

**Comment by eboyda** [comment]
OK, I have a solution using altair, which is built on vega, and is already included in the build environment. You get the full plotting capability of the altair library, and then streamlit just renders an altair object. Search for streamlit.altair_chart in the streamlit docs. 

Ref: https://altair-viz.github.io/getting_started/overview.html

The same thing goes with plotly - you can create whatever plotly object you like and then just render it with streamlit.plotly_chart. (Plotly is not included and has different stylings, so I'm not going there on this project).
